In [1]:
import pickle
import gzip
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from multiprocessing import Pool

from Helper_Code import *

In [2]:
# uploading the Complete Dataset
DataFrames = UploadDataSet("dataframes_list.pkl.gz")

In [29]:
import copy

DF = [copy.deepcopy(df) for df in DataFrames]

In [36]:
print(DF[0].columns)

Index(['X', 'Y', 'U', 'V', 'Ux', 'Uy', 'Vx', 'Vy', 'vor', 'Umean', 'Vmean',
       'Urms', 'Vrms', 'ufluc', 'wfluc', 'V16', 'V17'],
      dtype='object')

In [37]:
for df in DF:
    # Rename columns
    df.rename(columns={'Y': 'Z', 'V': 'W', 'Uy': 'Uz', 'Vy': 'Vz', 'Vmean': 'Wmean', 'Vrms': 'Wrms'}, inplace=True)
    
    # Drop columns V16 and V17
    df.drop(columns=['V16', 'V17'], inplace=True)

In [38]:
DF[0].columns

Index(['X', 'Z', 'U', 'W', 'Ux', 'Uz', 'Vx', 'Vz', 'vor', 'Umean', 'Wmean',
       'Urms', 'Wrms', 'ufluc', 'wfluc'],
      dtype='object')

In [28]:
DataFrames[0]

,X,Y,U,V,Ux,Uy,Vx,Vy,vor,Umean,Vmean,Urms,Vrms,ufluc,wfluc,V16,V17
0,0.314097,33.0326,3.46271,0.064536,-47.48990,99.7924,-74.9919,-44.9309,-174.7840,0.0,0.0,0.0,0.0,-0.269271,0.034541,450.314,0.558501
1,0.942293,33.0326,3.48953,0.013280,15.09410,60.6287,-92.4775,-18.0366,-153.1060,0.0,0.0,0.0,0.0,-0.255965,-0.020072,450.942,0.562828
2,1.535590,33.0326,3.50999,-0.018973,-27.05100,130.7770,-73.8357,21.3053,-204.6120,0.0,0.0,0.0,0.0,-0.238435,-0.050661,451.536,0.566128
3,2.128890,33.0326,3.50074,-0.057691,-7.20450,210.1000,-27.1359,56.5126,-237.2360,0.0,0.0,0.0,0.0,-0.245486,-0.087106,452.129,0.564635
4,2.722180,33.0326,3.45467,-0.068517,-4.44727,213.8220,18.4878,47.1953,-195.3340,0.0,0.0,0.0,0.0,-0.291523,-0.098783,452.722,0.557205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,86.549700,-32.9978,3.12049,0.117108,211.47100,214.5260,148.8580,194.3390,-65.6682,0.0,0.0,0.0,0.0,-0.166139,0.090287,536.550,0.503305
17996,87.142900,-32.9978,3.19540,0.200734,-59.11520,430.0830,62.3087,280.0960,-367.7750,0.0,0.0,0.0,0.0,-0.073013,0.178854,537.143,0.515388
17997,87.736100,-32.9978,3.02203,0.270963,-15.18650,770.1350,59.6885,331.3610,-710.4470,0.0,0.0,0.0,0.0,-0.241682,0.251439,537.736,0.487425
17998,88.329300,-32.9978,2.81474,0.214140,-6.64627,1037.3900,-37.8643,473.3800,-1075.2500,0.0,0.0,0.0,0.0,-0.439731,0.198363,538.329,0.453990
17999,88.957400,-32.9978,2.97971,0.205435,798.75400,638.9050,-113.9910,227.8960,-752.8960,0.0,0.0,0.0,0.0,-0.271324,0.200534,538.957,0.480599

In [39]:
DF[0]

,X,Z,U,W,Ux,Uz,Vx,Vz,vor,Umean,Wmean,Urms,Wrms,ufluc,wfluc
0,0.314097,33.0326,3.46271,0.064536,-47.48990,99.7924,-74.9919,-44.9309,-174.7840,0.0,0.0,0.0,0.0,-0.269271,0.034541
1,0.942293,33.0326,3.48953,0.013280,15.09410,60.6287,-92.4775,-18.0366,-153.1060,0.0,0.0,0.0,0.0,-0.255965,-0.020072
2,1.535590,33.0326,3.50999,-0.018973,-27.05100,130.7770,-73.8357,21.3053,-204.6120,0.0,0.0,0.0,0.0,-0.238435,-0.050661
3,2.128890,33.0326,3.50074,-0.057691,-7.20450,210.1000,-27.1359,56.5126,-237.2360,0.0,0.0,0.0,0.0,-0.245486,-0.087106
4,2.722180,33.0326,3.45467,-0.068517,-4.44727,213.8220,18.4878,47.1953,-195.3340,0.0,0.0,0.0,0.0,-0.291523,-0.098783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,86.549700,-32.9978,3.12049,0.117108,211.47100,214.5260,148.8580,194.3390,-65.6682,0.0,0.0,0.0,0.0,-0.166139,0.090287
17996,87.142900,-32.9978,3.19540,0.200734,-59.11520,430.0830,62.3087,280.0960,-367.7750,0.0,0.0,0.0,0.0,-0.073013,0.178854
17997,87.736100,-32.9978,3.02203,0.270963,-15.18650,770.1350,59.6885,331.3610,-710.4470,0.0,0.0,0.0,0.0,-0.241682,0.251439
17998,88.329300,-32.9978,2.81474,0.214140,-6.64627,1037.3900,-37.8643,473.3800,-1075.2500,0.0,0.0,0.0,0.0,-0.439731,0.198363
17999,88.957400,-32.9978,2.97971,0.205435,798.75400,638.9050,-113.9910,227.8960,-752.8960,0.0,0.0,0.0,0.0,-0.271324,0.200534

In [40]:
pd.to_pickle(DF, "DF_list_Correct.pkl.gz", compression='gzip')